services:
  sql-db:
    image: postgres
    env_file: .env
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d ${POSTGRES_DB} -U ${POSTGRES_USER}"]
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - ./persist/sql-db:/var/lib/postgresql/data

  web-app:
    build: ./web-app
    command: npm run dev
    env_file: .env
    healthcheck:
      test: "wget --no-verbose --tries=1 --spider 'http://localhost:${WEBAPP_PORT}' || exit 1"
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - ./web-app/src:/app/src/
    restart: always

  graphql-api:
    build: ./graphql-api
    command: npm run dev
    env_file: .env
    volumes:
      - ./graphql-api/src:/app/src/
    depends_on:
      sql-db:
        condition: service_healthy

  e2e:
    build: ./e2e
    volumes:
      - ./persist/e2e/report:/app/playwright-report
      - ./persist/e2e/results:/app/test-results
    depends_on:
      - gateway

  gateway:
    image: nginx
    restart: always
    ports:
      - ${GATEWAY_PORT}:80
    volumes:
      - ./gateway/:/etc/nginx/templates
    env_file: .env
    depends_on:
      - graphql-api
      - web-app
